### ISSUE TITLE
Comment Python Code. 

### ISSUE THREAD

**Issue by philipslan** [bnmnetp/runestone#584]
I know this isn't necessarily a "problem" with the code but I think it would be helpful for the code for each algorithm to be commented out so that students can better understand what might be occurring in the python function. For example in ActiveCode 1 (Recursively Counting Coins with Table Lookup (lst_change2)). The code is very simple but isn't necessarily readable or understandable. Take line 9: this line seems to be particularly powerful yet simple 
for i in [c for c in coinValueList if c <= change]:
I could probably guess that this is saying in the list of coins that are <= change do the following loop. Without much knowledge, this might be more confusing for novices.

**Comment by bnmnetp** [comment]
Hi, Thanks for the suggestion.

For the most part the code is documented in the text of the book, which is why we did not also comment the code.

Since this book is intended  for use in a second CS course we do assume that students are going to be familiar with Python, and common Python idioms like list comprehensions.

Brad

**Comment by philipslan** [comment]
I understand the code is explained in the paragraphs before or following a coding lens however I think having the comments in line would make sense for someone who is also following along and learning the algorithm. Just a suggestion. 

Best,
Philip
