### ISSUE TITLE
Invalid Login

### ISSUE THREAD

**Issue by sophos75** [bnmnetp/runestone#613]
The site claims invalid Login inspite of the username having been registered in the database as could be revealed by a lost password claim. 
It allows the password to be reset and use the account subsequently but on trying to login at a later time it claims that the username and password combination is invalid.

**Comment by bnmnetp** [comment]
Hi,

This issue has come up several times in the past.  In each case the problem boiled down to the user using their email address rather than their username when they went to login.  If you don't remember your username, let me know your email and I'll look it up for you.

If you are sure you are using your username and not your email could you tell me what your username is so I can investiate further?  I cannot replicate this problem myself, so a reliably not working username would help a lot.

Thanks,

Brad

**Comment by bnmnetp** [comment]
I'm assuming that the problem is resolved since I haven't heard anything more.

**Comment by sophos75** [comment]
I Thank you for addressing the issue and I apologise for being a lazy prick
in re the issue and the delayed response to your mail.

**Comment by Birdzview** [comment]
I have the same problem: "Invalid Login" 
Please help.
