### ISSUE TITLE
Old Student List

### ISSUE THREAD

**Issue by rosewcs345** [bnmnetp/runestone#619]
After re-building my course for the fall, for some strange reason when I click the link for  
List/Create Assignments (http://interactivepython.org/runestone/assignments/index)
I get a list of my old students.
This seems to be the ONLY place where this happens 
(I've clicked around everywhere else)
Is there something I can/should do about this? 
THANKS!!

**Comment by bnmnetp** [comment]
No, you are #2 with this request.

The List/Create Assignments does not look at the course start date.  But I added a database field so that I could mark students inactive.  I don't want to delete them because then they lose the ability to come back and look at old code.

I recommend just building  a new class, but I also realize that putting together the assignments takes a fair amount of work.  Please let me know which course, and I can mark all of your students inactive manually.  Also let me know your username so I can keep you active.

If enough people want this I will build a link on the instructor dashboard for you to do it yourself.

Brad

**Comment by bnmnetp** [comment]
Nevermind, I figured out the course and instructor username.  You should not see the students under List/Create anymore.

**Comment by rosewcs345** [comment]
Wow!  Thanks so much!

On Fri, Aug 7, 2015 at 3:18 PM, Brad Miller <notifications@github.com>
wrote:

> Nevermind, I figured out the course and instructor username. You should
> not see the students under List/Create anymore.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bnmnetp/runestone/issues/619#issuecomment-128799351>.
>



-- 
-- 

*Rose Williams*

*Lecturer*

*Department of Computer Science*

*Binghamton University*

*(607) 777-7702*

*-----------------------------------------------*


*We are what we think.  *

*All that we are arises** with*
* our thoughts.  *

*With our thoughts,** we** make the world.*



*Shakyamuni** Buddha*
