### ISSUE TITLE
Will Not Recognize Password

### ISSUE THREAD

**Issue by clairedemars1** [bnmnetp/runestone#620]
This is for the interactive version of How to Think Like a Computer Scientist. It wouldn't accept my password before I reset the password and won't accept it now, after I reset it.

**Comment by bnmnetp** [comment]
Please make sure you are using your username and NOT your email address to log in.

**Comment by clairedemars1** [comment]
That fixed my problem: I had forgotten my username wasn't just my email
address since I usually just do that.

 Is there a reason we can't use an email address as a username for this
book, when many other sites allow it? It would allow more consistency
making it easier to remember one's username.

I think it's also a little confusing that when once you're logged in, if
you click on the silhouette of a head in the upper right hand corner, it
lists your email across the top of the drop-down menu, as if your email
were your username. I think it would be better if it was the username
instead.

Anyway, thanks very much for being so quick to help me with these questions
I had, and I'm finding the book really useful!

Claire

**Comment by bnmnetp** [comment]
The reason is that that is the way the web2py framework does it.  I didn't want to spend the development time to make my own login system so I just took theirs out of the box.   I'm working on a new backend with a new framework.  That one will let you use your email, but that probably won't be done until next summer.

You make a good point about the name that shows up under the user menu. I think I can fix that pretty easily.

**Comment by clairedemars1** [comment]
Thanks!
